if(EXISTS "/Users/luca/Library/Mobile Documents/com~apple~CloudDocs/Dev/egoboo/idlib_original/idlib-parsing-expression/tests/idlib-parsing-expression-tests-executable[1]_tests.cmake")
  include("/Users/luca/Library/Mobile Documents/com~apple~CloudDocs/Dev/egoboo/idlib_original/idlib-parsing-expression/tests/idlib-parsing-expression-tests-executable[1]_tests.cmake")
else()
  add_test(idlib-parsing-expression-tests-executable_NOT_BUILT idlib-parsing-expression-tests-executable_NOT_BUILT)
endif()
