if(EXISTS "/Users/luca/Library/Mobile Documents/com~apple~CloudDocs/Dev/egoboo/idlib_original/idlib-document/tests/idlib-document-tests-executable[1]_tests.cmake")
  include("/Users/luca/Library/Mobile Documents/com~apple~CloudDocs/Dev/egoboo/idlib_original/idlib-document/tests/idlib-document-tests-executable[1]_tests.cmake")
else()
  add_test(idlib-document-tests-executable_NOT_BUILT idlib-document-tests-executable_NOT_BUILT)
endif()
