if(EXISTS "/Users/luca/Library/Mobile Documents/com~apple~CloudDocs/Dev/egoboo/idlib_original/idlib-math-geometry/tests/idlib-math-geometry-tests-executable[1]_tests.cmake")
  include("/Users/luca/Library/Mobile Documents/com~apple~CloudDocs/Dev/egoboo/idlib_original/idlib-math-geometry/tests/idlib-math-geometry-tests-executable[1]_tests.cmake")
else()
  add_test(idlib-math-geometry-tests-executable_NOT_BUILT idlib-math-geometry-tests-executable_NOT_BUILT)
endif()
