if(EXISTS "/Users/luca/Library/Mobile Documents/com~apple~CloudDocs/Dev/egoboo/idlib_original/idlib-signal/tests/idlib-signal-tests-executable[1]_tests.cmake")
  include("/Users/luca/Library/Mobile Documents/com~apple~CloudDocs/Dev/egoboo/idlib_original/idlib-signal/tests/idlib-signal-tests-executable[1]_tests.cmake")
else()
  add_test(idlib-signal-tests-executable_NOT_BUILT idlib-signal-tests-executable_NOT_BUILT)
endif()
